import { deepFreeze } from '../../lib/obj_utils.js';

export const SIMOBJECTDEBUGTYPES_ENUM = {
  DEBUG_DEBUG: "DEBUG_DEBUG",
  DEBUG_INFO: "DEBUG_INFO",
  DEBUG_WARNING: "DEBUG_WARNING",
  DEBUG_ERROR: "DEBUG_ERROR"
}
deepFreeze(SIMOBJECTDEBUGTYPES_ENUM);

// @ts-ignore
export const SIMOBJECTDEBUGTYPES_ENUM_VALIDATION = Object.keys(SIMOBJECTDEBUGTYPES_ENUM).map(key => SIMOBJECTDEBUGTYPES_ENUM[key]);
