import { deepFreeze } from '../../lib/obj_utils.js';

export const SIMOBJECTTYPESEXCLUDEDFROMLEDGER_ENUM = {
  DEBUG: "DEBUG_",
  EXTRA: "EXTRA_"
}
deepFreeze(SIMOBJECTTYPESEXCLUDEDFROMLEDGER_ENUM);

// @ts-ignore
export const SIMOBJECTTYPESEXCLUDEDFROMLEDGER_ENUM_VALIDATION =
  Object.keys(SIMOBJECTTYPESEXCLUDEDFROMLEDGER_ENUM).map(key => SIMOBJECTTYPESEXCLUDEDFROMLEDGER_ENUM[key]);
