export { SimObjectTypes_WithPrincipal_enum };

import { deepFreeze, ensureArrayValuesAreUnique } from '../../../lib/obj_utils.js';

const SimObjectTypes_WithPrincipal_enum = {
//#region SimObjectEnum_WITHPRINCIPAL__codeid_EXTERNAL
BS_CASH__BANKACCOUNT_FINANCIALACCOUNT : "BS_CASH__BANKACCOUNT_FINANCIALACCOUNT",  // (ITA) Depositi_bancari_e_postali
BS_CREDIT__ACCRUALSCREDITS : "BS_CREDIT__ACCRUALSCREDITS",  // (ITA) Ratei_attivi
BS_CREDIT__FINANCIALCREDITS__VSOTHERS : "BS_CREDIT__FINANCIALCREDITS__VSOTHERS",  // (ITA) Crediti_finanziari__Verso_altri
BS_CREDIT__FINANCIALCREDITS__VSSHAREHOLDERS : "BS_CREDIT__FINANCIALCREDITS__VSSHAREHOLDERS",  // (ITA) Crediti_finanziari__Verso_soci
BS_CREDIT__FINANCIALCREDITS__VSSHAREHOLDERSFORCONTRIBUTIONSDUECALLED : "BS_CREDIT__FINANCIALCREDITS__VSSHAREHOLDERSFORCONTRIBUTIONSDUECALLED",  // (ITA) Crediti_finanziari__Verso_soci_per_versamenti_dovuti_parte_richiamata
BS_CREDIT__FINANCIALCREDITS__VSSHAREHOLDERSFORCONTRIBUTIONSDUETOBECALLED : "BS_CREDIT__FINANCIALCREDITS__VSSHAREHOLDERSFORCONTRIBUTIONSDUETOBECALLED",  // (ITA) Crediti_finanziari__Verso_soci_per_versamenti_dovuti_parte_da_richiamare
BS_CREDIT__GENERICCREDITS__VSOTHERS : "BS_CREDIT__GENERICCREDITS__VSOTHERS",  // (ITA) Crediti_generici__Verso_altri
BS_CREDIT__GENERICCREDITS__VSSUPPLIERS : "BS_CREDIT__GENERICCREDITS__VSSUPPLIERS",  // (ITA) Crediti_generici__Acconti
BS_CREDIT__GENERICFINANCIALINSTRUMENT_ASSETS__FORTRADING : "BS_CREDIT__GENERICFINANCIALINSTRUMENT_ASSETS__FORTRADING",  // (ITA) Altri_titoli__Attivita_finanziarie_non_immobilizzate
BS_CREDIT__GENERICFINANCIALINSTRUMENT_ASSETS__TOHOLD : "BS_CREDIT__GENERICFINANCIALINSTRUMENT_ASSETS__TOHOLD",  // (ITA) Altri_titoli__Immobilizzazioni_finanziarie
BS_CREDIT__PREPAYMENTS : "BS_CREDIT__PREPAYMENTS",  // (ITA) Risconti_attivi
BS_CREDIT__TAXCREDITS : "BS_CREDIT__TAXCREDITS",  // (ITA) Crediti_tributari__Vari
BS_CREDIT__TAXCREDITS__PREPAIDTAX : "BS_CREDIT__TAXCREDITS__PREPAIDTAX",  // (ITA) Crediti_tributari__Imposte_anticipate
BS_CREDIT__TRADERECEIVABLECREDITS : "BS_CREDIT__TRADERECEIVABLECREDITS",  // (ITA) Crediti_verso_clienti
BS_CREDIT__VATCREDITS : "BS_CREDIT__VATCREDITS",  // (ITA) Crediti_tributari__IVA
BS_EQUITYINSTRUMENTS__EQUITYINSTRUMENTS_ASSETS__FINANCIALINVESTMENT : "BS_EQUITYINSTRUMENTS__EQUITYINSTRUMENTS_ASSETS__FINANCIALINVESTMENT",  // (ITA) Partecipazioni__Attivita_finanziarie_non_immobilizzate
BS_EQUITYINSTRUMENTS__EQUITYINSTRUMENTS_ASSETS__PARTICIPATION : "BS_EQUITYINSTRUMENTS__EQUITYINSTRUMENTS_ASSETS__PARTICIPATION",  // (ITA) Partecipazioni__Immobilizzazioni_finanziarie
BS_LIABILITY__ACCRUALSDEBTS : "BS_LIABILITY__ACCRUALSDEBTS",  // (ITA) Ratei_passivi
BS_LIABILITY__DEFERREDINCOME : "BS_LIABILITY__DEFERREDINCOME",  // (ITA) Risconti_passivi
BS_LIABILITY__EMPLOYEEPROVISIONS : "BS_LIABILITY__EMPLOYEEPROVISIONS",  // (ITA) Trattamento_fine_rapporto
BS_LIABILITY__FINANCIALDEBTS__BOND : "BS_LIABILITY__FINANCIALDEBTS__BOND",  // (ITA) Debiti_finanziari__Obbligazioni
BS_LIABILITY__FINANCIALDEBTS__BONDCONVERTIBLE : "BS_LIABILITY__FINANCIALDEBTS__BONDCONVERTIBLE",  // (ITA) Debiti_finanziari__ObbligazioniConvertibili
BS_LIABILITY__FINANCIALDEBTS__CONTRACTFINANCING : "BS_LIABILITY__FINANCIALDEBTS__CONTRACTFINANCING",  // (ITA) Debiti_finanziari__Verso_banche__Anticipo_su_contratti
BS_LIABILITY__FINANCIALDEBTS__INVOICEFINANCING : "BS_LIABILITY__FINANCIALDEBTS__INVOICEFINANCING",  // (ITA) Debiti_finanziari__Verso_banche__Smobilizzo_crediti
BS_LIABILITY__FINANCIALDEBTS__LEASING : "BS_LIABILITY__FINANCIALDEBTS__LEASING",  // (ITA) Debiti_finanziari__Leasing
BS_LIABILITY__FINANCIALDEBTS__LOAN : "BS_LIABILITY__FINANCIALDEBTS__LOAN",  // (ITA) Debiti_finanziari__Verso_banche__Finanziamenti
BS_LIABILITY__FINANCIALDEBTS__OVERDRAFT : "BS_LIABILITY__FINANCIALDEBTS__OVERDRAFT",  // (ITA) Debiti_finanziari__Verso_banche__Fidi_di_cassa
BS_LIABILITY__FINANCIALDEBTS__VSOTHERS : "BS_LIABILITY__FINANCIALDEBTS__VSOTHERS",  // (ITA) Debiti_finanziari__Verso_altri
BS_LIABILITY__FINANCIALDEBTS__VSSHAREHOLDERS : "BS_LIABILITY__FINANCIALDEBTS__VSSHAREHOLDERS",  // (ITA) Debiti_finanziari__Verso_soci
BS_LIABILITY__GENERICDEBTS__VSCUSTOMERS : "BS_LIABILITY__GENERICDEBTS__VSCUSTOMERS",  // (ITA) Debiti_generici__Acconti
BS_LIABILITY__GENERICDEBTS__VSEMPLOYEES : "BS_LIABILITY__GENERICDEBTS__VSEMPLOYEES",  // (ITA) Debiti_generici__Verso_dipendenti
BS_LIABILITY__GENERICDEBTS__VSOTHERS : "BS_LIABILITY__GENERICDEBTS__VSOTHERS",  // (ITA) Debiti_generici__Verso_altri
BS_LIABILITY__OTHERPROVISIONS : "BS_LIABILITY__OTHERPROVISIONS",  // (ITA) Fondi_rischi_e_oneri
BS_LIABILITY__SOCIALSECURITYPAYABLEDEBTS : "BS_LIABILITY__SOCIALSECURITYPAYABLEDEBTS",  // (ITA) Debiti_verso_Istituti_di_previdenza
BS_LIABILITY__TAXDEBTS : "BS_LIABILITY__TAXDEBTS",  // (ITA) Debiti_tributari__Vari
BS_LIABILITY__TRADEPAYABLEDEBTS : "BS_LIABILITY__TRADEPAYABLEDEBTS",  // (ITA) Debiti_verso_Fornitori
BS_LIABILITY__VATDEBTS : "BS_LIABILITY__VATDEBTS",  // (ITA) Debiti_tributari__IVA
// skip
// skip
// skip
// skip
//#endregion SimObjectEnum_WITHPRINCIPAL__codeid_EXTERNAL
}
deepFreeze(SimObjectTypes_WithPrincipal_enum);
ensureArrayValuesAreUnique(Object.values(SimObjectTypes_WithPrincipal_enum));
