import { deepFreeze } from '../lib/obj_utils.js';

/**
 * inspired by https://mikemcl.github.io/decimal.js-light/#modes
 * @enum {string}
 * @readonly
 */
export const ROUNDING_MODES = {
  HALF_EVEN: "HALF_EVEN",   // Rounds 0.5 towards nearest neighbour. If equidistant, rounds 0.5 towards even neighbour: e.g., 2.5 to 2, 3.5 to 4, -2.5 to -2, -3.5 to -4
  HALF_UP: "HALF_UP"        // Rounds 0.5 towards nearest neighbour. If equidistant, rounds 0.5 away from zero: e.g., 2.5 to 3, 3.5 to 4, -2.5 to -3, -3.5 to -4
};
Object.freeze(ROUNDING_MODES);

//#region debug and release config
// If true, the debug validations and checks are disabled; this should be true ONLY IF YOU REALLY NEED IT in release mode, to speed up execution
// (not recommended, because it can hide validation problems that can't be easily caught otherwise)
export const RELEASE__DISABLE_SANITIZATIONS_VALIDATIONS_AND_CHECKS = false;

// If true, the validation of the data is disabled in 'schema_validation_utils.js/validate()';
// not recommended to set this to true, is usable for testing purposes or (maybe) to speed up the execution of the engine, thanks to the absence of validation
export const DISABLE_VALIDATION = false;
//#endregion debug and release config

//#region ASCII 31 unprintable (invisible hidden) control character + regexp
// This character is used - when needed - to distinguish strings internally generated from those generated by the user
// This works because the character is removed by the input json file
export const UNPRINTABLE_CHAR = String.fromCharCode(31);
export const UNPRINTABLE_CHAR_REGEXP = /\u001f/g;
export const JSON_UNPRINTABLE_CHAR_REGEXP = /\\u001f/g;
//#endregion ASCII 31 invisible unprintable control character + regexp

//#region config used by engine and Excel UI
export const SIMULATION_NAME = '$';
export const SCENARIO_BASE = 'base';
export const FML_PREFIX = [  // prefix to mark formulas in the Excel UI and in the engine
  '#',  // hash, easiest to type on most keyboard layout
  //'`',  // backtick, we could have used it, but it is more difficult to type on some keyboard layouts
];
deepFreeze(FML_PREFIX);
export const ARRAY_ARITHMETIC_PREFIX = '<';  // prefix to mark formulas in the Excel UI and in the engine
//#endregion config used by engine and Excel UI

//#region modules config, used by engine and Excel UI
export const DEFAULT_UNIT_ID = 'CompanyA';

export const BS_CASH__BANKACCOUNT_FINANCIALACCOUNT__NAME = 'cash_account_1';
//#endregion modules config, used by engine and Excel UI

//#region internal engine config
// Number of the years from today to set Simulation End Date, if no other value to set this date is provided
export const DEFAULT_NUMBER_OF_YEARS_FROM_TODAY = 5;
// Rounding mode to use when storing numbers in the ledger and in other places that requires rounding
export const ROUNDING_MODE = ROUNDING_MODES.HALF_EVEN;
// Scale to use when doing decimal calculations with BigInt (SCALE)
export const BIGINT_DECIMAL_SCALE = 10;  // scale of 10 means that numbers are stored with 10 decimal places of precision
// Decimal places to use when storing numbers in the ledger (PRECISION)
export const ACCOUNTING_DECIMAL_PLACES = 4;

// config used during init of Settings and Drivers classes
export const IMMUTABLEPREFIX__IMMUTABLE_WITHOUT_DATES = '$$';
export const IMMUTABLEPREFIX__IMMUTABLE_WITH_DATES = '$';

// Formula and JSON cache size
//export const FML_CACHE_SIZE = 10_000;  // disabled, because formulas doesn't have a cache but are contained, one by one, in `FmlObj` objects
export const JSON_CACHE_SIZE = 10_000;
export const JSON_CACHE_SIZE__MAX_CACHEABLE_CHARS = 250_000; // ~250KB to ~500KB of memory occupation
//#endregion internal engine config
