// reserved names for TaskLocks

export { TaskLocks_Names };

import { deepFreeze, ensureArrayValuesAreUnique } from '../lib/obj_utils.js';

const TaskLocks_Names = {
  SIMULATION__SETTINGS: 'SIMULATION__SETTINGS',
  SIMULATION__DEFAULT_ACTIVE_SETTINGS: 'SIMULATION__DEFAULT_ACTIVE_SETTINGS',
  SIMULATION__INTERCOMPANY_CASHMANAGER__DAILY_ACTIVITY: 'SIMULATION__INTERCOMPANY_CASHMANAGER__DAILY_ACTIVITY',
  SIMULATION__EURIBOR_RATE_LIST__INFO: 'SIMULATION__EURIBOR_RATE_LIST__INFO',
  SIMULATION__EBITDA__DAILY_INFO: 'SIMULATION__EBITDA__DAILY_INFO',
  SIMULATION__NWC__DAILY_ACTIVITY: 'SIMULATION__NWC__DAILY_ACTIVITY',

  UNIT__TAXES_COMPUTATION__DAILY_ACTIVITY: 'UNIT__TAXES_COMPUTATION__DAILY_ACTIVITY',
  UNIT__TAXES_PAYMENT__DAILY_ACTIVITY: 'UNIT__TAXES_PAYMENT__DAILY_ACTIVITY',
  UNIT__TREASURY__DAILY_ACTIVITY: 'UNIT__TREASURY__DAILY_ACTIVITY',
  UNIT__NWC__DAILY_ACTIVITY: 'UNIT__NWC__DAILY_ACTIVITY',
};
deepFreeze(TaskLocks_Names);
ensureArrayValuesAreUnique(Object.values(TaskLocks_Names));
