export { UNIT_OBJECTS_NAMES };

//#region UNIT_OBJECTS_NAMES
const UNIT_OBJECTS_NAMES = {};
UNIT_OBJECTS_NAMES.BS_CASH__BANKACCOUNT_FINANCIALACCOUNT = 'cash_account_1';
//#endregion UNIT_OBJECTS_NAMES
