export { SHAREDCONSTANTS_RESERVEDNAMES };

import { deepFreeze } from '../../lib/obj_utils.js';

const SHAREDCONSTANTS_RESERVEDNAMES = {};
SHAREDCONSTANTS_RESERVEDNAMES.TAXES = 'taxes';
SHAREDCONSTANTS_RESERVEDNAMES.TREASURY = 'treasury';
deepFreeze(SHAREDCONSTANTS_RESERVEDNAMES);
